************************************************************************                          Test Failure Feedback ************************************************************************
Failed Test: 6. Test the interface of AlphaBetaPlayer.get_move()
----------------------------------------------------------------------
AssertionError: False is not true : The AlphaBetaPlayer.get_move() function failed as player 1 on an empty board. It should return coordinates on the game board for the location of the agent's next move. The move must be one of the legal moves on the current game board. Your function returned (-1, -1) which is not in the list of legal moves [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (7, 0), (8, 0), (0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (0, 3), (1, 3), (2, 3), (3, 3), (4, 3), (5, 3), (6, 3), (7, 3), (8, 3), (0, 4), (1, 4), (2, 4), (3, 4), (4, 4), (5, 4), (6, 4), (7, 4), (8, 4), (0, 5), (1, 5), (2, 5), (3, 5), (4, 5), (5, 5), (6, 5), (7, 5), (8, 5), (0, 6), (1, 6), (2, 6), (3, 6), (4, 6), (5, 6), (6, 6), (7, 6), (8, 6), (0, 7), (1, 7), (2, 7), (3, 7), (4, 7), (5, 7), (6, 7), (7, 7), (8, 7), (0, 8), (1, 8), (2, 8), (3, 8), (4, 8), (5, 8), (6, 8), (7, 8), (8, 8)]

Failed Test: 7. Test functionality of AlphaBetaPlayer.alphabeta()
----------------------------------------------------------------------
AssertionError: False is not true : Your AlphaBetaAgent.alphabeta function did not call the heuristic evaluation function in all of the expected set of leaf nodes configurations in the game tree as player 1. Make sure that you are using the self.score() method to evaluate the board (not calling one of your heuristic functions directly) and verify your stopping conditions. Leaf nodes are shown as (player_1, player_2) location pairs. Optional nodes may or may not be visited depending on your termination test.

Expected leaf nodes:
{((0, 0), (5, 6)), ((4, 0), (5, 6)), ((1, 3), (5, 6)), ((0, 2), (5, 6))}
Optional leaf nodes:
set()
Leaf nodes your agent evaluated:
{((0, 2), (4, 8)), ((4, 0), (4, 8)), ((0, 0), (7, 7)), ((0, 2), (7, 5)), ((1, 3), (7, 7)), ((4, 0), (3, 5)), ((0, 2), (3, 5)), ((4, 0), (6, 8)), ((4, 0), (7, 5)), ((1, 3), (6, 8)), ((0, 0), (3, 5)), ((1, 3), (3, 5)), ((4, 0), (7, 7)), ((0, 0), (7, 5)), ((0, 2), (7, 7)), ((1, 3), (7, 5)), ((0, 0), (4, 8)), ((0, 2), (6, 8)), ((1, 3), (4, 8)), ((0, 0), (6, 8))}
Skipped nodes:
{((0, 0), (5, 6)), ((1, 3), (5, 6)), ((4, 0), (5, 6)), ((0, 2), (5, 6))}
Extra nodes:
{((0, 0), (7, 7)), ((4, 0), (7, 7)), ((1, 3), (7, 5)), ((1, 3), (4, 8)), ((0, 2), (4, 8)), ((0, 2), (7, 5)), ((0, 0), (3, 5)), ((4, 0), (3, 5)), ((0, 2), (6, 8)), ((0, 0), (6, 8)), ((1, 3), (7, 7)), ((4, 0), (7, 5)), ((0, 2), (3, 5)), ((4, 0), (6, 8)), ((0, 0), (7, 5)), ((0, 0), (4, 8)), ((4, 0), (4, 8)), ((1, 3), (3, 5)), ((0, 2), (7, 7)), ((1, 3), (6, 8))}

Test Case Details:
------------------
Heuristic: open_move_score
Depth limit: 1
Initial Board State:
     0   1   2   3   4   5   6   7   8
0  |   |   |   |   |   |   |   |   |   |
1  |   |   |   |   |   |   |   |   |   |
2  |   | 1 |   | - | - | - | - |   |   |
3  |   |   |   | - | - |   | - | - |   |
4  |   |   | - | - | - |   | - | - |   |
5  |   |   | - | - | - | - | 2 |   |   |
6  |   |   | - |   | - |   | - | - |   |
7  |   |   |   |   | - |   |   |   |   |
8  |   |   |   |   |   |   |   |   |   |

game._board_state:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 11]

Failed Test: 14. Submission includes heuristic_analysis.pdf
----------------------------------------------------------------------
AssertionError: False is not true : You must submit a report named heuristic_analysis.pdf for review.

Failed Test: 15. Submission includes research_review.pdf
----------------------------------------------------------------------
AssertionError: False is not true : You must submit a report named research_review.pdf for review.

************************************************************************
                          Test Result Summary
************************************************************************

1. Test output interface of MinimaxPlayer.minimax():                   .
2. Test functionality of MinimaxPlayer.minimax():                      .
3. Test that minimax() raises SearchTimeout when the timer expires:    .
4. Test that MinimaxPlayer successfully plays a full game:             .
5. Test interface of AlphaBetaPlayer.alphabeta():                      .
6. Test the interface of AlphaBetaPlayer.get_move():                   F
7. Test functionality of AlphaBetaPlayer.alphabeta():                  F
8. Test that alphabeta() raises SearchTimeout when the timer expires:  .
9. Test iterative deepening in AlphaBetaPlayer.get_move():             .
10. Test that AlphaBetaPlayer successfully plays a full game:          .
11. Test output interface of custom_score():                           .
12. Test output interface of custom_score_2():                         .
13. Test output interface of custom_score_3():                         .
14. Submission includes heuristic_analysis.pdf:                        F
15. Submission includes research_review.pdf:                           F

------------------------------------------------------------------------
            . - Test Passed    F - Test Failed    E - Error

Details are available in isolation-result-71623.json.

If you would like this version of the project to be reviewed,
submit isolation-71623.zip to the reviews website.